#!/usr/bin/env bash
# Configure an NGINX Server

#Install Nginx Server
sudo apt-get update
sudo apt-get install -y nginx

#Change the ownership and permission of the var/www/html directory and subdirectories to the current user
sudo chown -R "$USER":"$USER" /var/www
sudo chown -R "$USER":"$USER" /etc/nginx

#Give execute permission to the user (owner) of the file
sudo chmod -R 755 /var/www
sudo chmod -R 755 /etc/nginx

#Create a new index page
echo 'Hello World!' > /var/www/html/index.html

#Configure redirection
#sed -i 's/index index.html;/index index.html;\n\n\trewrite ^\/redirect_me https:\/\/nairaland.com permanent;/' /etc/nginx/sites-enabled/default
sed -i 's/index index.html;/index index.html;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/nairaland.com;\n\t}/' /etc/nginx/sites-enabled/default


# Reload the Server
service nginx restart
