#!/usr/bin/env bash
# Configure an NGINX Server

#Install Nginx Server
sudo apt-get update
sudo apt-get install -y nginx

#Create a new index page
echo 'Hello World!' > /var/www/html/index.html

#Configure Redirection
replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;"
sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-enabled/default

# Reload the Server
service nginx restart
