#!/usr/bin/env bash
# Configure an NGINX Server

#Install Nginx Server
sudo apt-get update
sudo apt-get install nginx -y

#Create the website directory
mkdir /etc/nginx/html

#Create the index and 404 page
touch /etc/nginx/html/index.html

#Create 404 Error Page
touch /etc/nginx/html/404.html

#Write Hello World in the index page
echo 'Hello World!' > /etc/nginx/html/index.html

#Write the error message in the 404 error page
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

#create configuration file
printf %s "		server {
		listen 80 default_server;
		listen [::]:80 default_server;

		root /etc/nginx/html;
		index index.html index.htm;

		error_page 404 /404.html;
		location /404 {
			root /etc/nginx/html;
			internal;
		}

		location /redirect_me {
			return 301 https://www.youtube.com;
		}
	    }
" > /etc/nginx/sites-enabled/default


# Restart the Server
sudo service nginx restart
