#!/usr/bin/env bash
# Configure an NGINX Server

#Install Nginx Server
sudo apt-get update
sudo apt-get install nginx -y

#Create a new index page
echo 'Hello World!' > /var/www/html/index.html

#Create the error page
echo "Ceci n'est pas une page" > /var/www/html/404.html

#Configure redirection
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

#Configure the 404 error directive
string_new="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_new/" /etc/nginx/sites-enabled/default

# Reload the Server
service nginx reload
