#!/usr/bin/env bash
# Configure load balancer to serve distribute traffic among two webserver
#Install software properties common package
sudo apt install software-properties-common -y

#Reference the HAProxy Repository
sudo add-apt-repository ppa:vbernat/haproxy-2.0

#Install HAProxy
sudo apt update
sudo apt install haproxy -y

#Configure haproxy
sudo sh -c 'printf %s "frontend websites
   bind *:80
   mode http
   default_backend webservers
backend webservers
   balance roundrobin
   mode http
   server webserver1 54.172.175.168:80
   server webserver2 54.152.144.111:80" >> /etc/haproxy/haproxy.cfg'

#Enable management via the init script
sudo ch -c 'echo "ENABLED=1" >> /etc/default/haproxy'

# Restart HAProxy
sudo service haproxy start
